expressive/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('lexicon/', include('lexicon.urls')),
    path('admin/', admin.site.urls),
]

lexicon/urls.py
from django.urls import path

from . import views


app_name = 'lexicon'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('<int:pk>/', views.TermDetail.as_view(), name='term_detail'),
    path(
        '<int:pk>/<str:show_example_sentences>',
        views.TermDetail.as_view(),
        name='term_detail_add_sentence'),
    path('random/', views.random_term, name='random_term'),
    path('<int:term_id>/add_sentence/', views.add_sentence, name='add_sentence'),
]

lexicon/models.py
from django.db import models


class Term(models.Model):
    term_text = models.CharField(max_length=200)
    priority = models.IntegerField(default=1)

    def __str__(self):
        return self.term_text


class Sentence(models.Model):
    term = models.ForeignKey(Term, on_delete=models.CASCADE)
    sentence_text = models.CharField(max_length=500)

    def __str__(self):
        return self.sentence_text

lexicon/views.py
import random
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Term


class Index(generic.ListView):
    model = Term
    template_name = 'lexicon/index.html'

    def get_queryset(self):
        return Term.objects.order_by('term_text')


class TermDetail(generic.DetailView):
    model = Term
    template_name = 'lexicon/term_detail.html'

    def get_context_data(self, **kwargs):
        context = super(TermDetail, self).get_context_data(**kwargs)
        kwargs = self.kwargs

        if 'show_example_sentences' in kwargs \
                and kwargs['show_example_sentences'] == 'show_example_sentences':
            context['show_example_sentences'] = True
        else:
            context['show_example_sentences'] = False

        return context


def random_term(request):
    term = random.choice(Term.objects.all())
    return HttpResponseRedirect(reverse('lexicon:term_detail', args=(term.id,)))


def add_sentence(request, term_id):
    term = get_object_or_404(Term, pk=term_id)
    kwargs = {'pk': term_id}
    try:
        term.sentence_set.create(sentence_text=request.POST['sentence_text'])
        kwargs['show_example_sentences'] = 'show_example_sentences'
    except:
        pass
        kwargs['show_example_sentences'] = 'error'

    return HttpResponseRedirect(
        reverse('lexicon:term_detail_add_sentence', kwargs=kwargs))

lexicon/templates/lexicon/index.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'lexicon/style.css' %}" />
    <title>Lexicon</title>
</head>

<body>
<div id="container">

<h1>Expressive: Lexicon</h1>
<div id="menu">
    <a href="{% url 'lexicon:random_term' %}">random</a>
    <a href="{% url 'lexicon:index' %}">index</a>
    <a href="/admin">admin</a>
</div>
<br />
<div id="content">
{% if term_list %}
{% for term in term_list %}
<h2><a href="{% url 'lexicon:term_detail' term.id %}">{{ term.term_text }}</a></h2>
{% endfor %}
{% endif %}
</div>
</div>
</body>

lexicon/templates/lexicon/term_detail.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'lexicon/style.css' %}" />
    <script src="{% static 'lexicon/jquery-3.3.1.min.js' %}"></script>
    <script>

        $(document).ready(function(){

            $("#example_sentence_toggle").click(function(){
                $("#example_sentences").toggle("fast");
            });

        });
    </script>
    <title>Lexicon</title>
</head>

<body>

<div id="container">
<h1>Expressive: Lexicon</h1>

<div id="menu">
    <a href="{% url 'lexicon:random_term' %}">random</a>
    <a href="{% url 'lexicon:index' %}">index</a>
    <a href="/admin">admin</a>
</div>
<br />
<div id="content">
<h2>Term: {{ term.term_text }}</h2>

<form action="{% url 'lexicon:add_sentence' term.id %}" method="post">
    {% csrf_token %}
    <label for="sentence_text">Example sentence:</label><br />
    <textarea name="sentence_text" id="sentence_text" rows="4"></textarea><br />
    <input id="add_sentence_button" type="submit" value="Save" style="font-size:20px" />
</form>


<a id="example_sentence_toggle" href="#">Show example sentences</a>

{% if show_example_sentences %}
    <div id="example_sentences">
{% else %}
    <div id="example_sentences" style="display: none;">
{% endif %}

<h3>Example sentences</h3>
<p>
{% for sentence in term.sentence_set.all %}
    {{ sentence.sentence_text }}<br /><br />
{% endfor %}
</p>
</div>
</div>
</div>

</body>